<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="systemmodel" nsURI="systemmodel.meta" nsPrefix="hu.karaszi.ec.centralunit.controller.model">
  <eClassifiers xsi:type="ecore:EClass" name="Device" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="health" eType="#//DeviceStatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sensor" eSuperTypes="#//Device">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="#//SensorState"
        defaultValueLiteral="NORMAL"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensortype" lowerBound="1"
        eType="#//SensorType" eOpposite="#//SensorType/sensor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="affectedBy" upperBound="-1"
        eType="#//Actuator" eOpposite="#//Actuator/affects"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minReadable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxReadable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastMeasurement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actuator" eSuperTypes="#//Device">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="#//ActuatorState"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="performance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actuatorType" lowerBound="1"
        eType="#//ActuatorType" eOpposite="#//ActuatorType/actuator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="affects" upperBound="-1"
        eType="#//Sensor" eOpposite="#//Sensor/affectedBy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ActuatorState">
    <eLiterals name="ON"/>
    <eLiterals name="OFF"/>
    <eLiterals name="UNKNOWN"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SensorState">
    <eLiterals name="LOW_FATAL"/>
    <eLiterals name="LOW_CRITICAL"/>
    <eLiterals name="NORMAL"/>
    <eLiterals name="HIGH_CRITICAL"/>
    <eLiterals name="HIGH_FATAL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DeviceStatus">
    <eLiterals name="OK"/>
    <eLiterals name="DEGRADED"/>
    <eLiterals name="ERROR"/>
    <eLiterals name="UNKNOWN"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActuatorType" eSuperTypes="#//Template">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAdjustable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actuator" upperBound="-1"
        eType="#//Actuator" eOpposite="#//Actuator/actuatorType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SensorType" eSuperTypes="#//Template">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensor" upperBound="-1"
        eType="#//Sensor" eOpposite="#//Sensor/sensortype"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Template" abstract="true" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
