<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="systemmodel" nsURI="systemmodel.meta" nsPrefix="hu.karaszi.ec.centralunit.controller.model">
  <eClassifiers xsi:type="ecore:EClass" name="Device" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceHealth" eType="#//DeviceHealth"
        defaultValueLiteral="UNKNOWN"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceState" eType="#//DeviceState"
        defaultValueLiteral="INACTIVE"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastDeviceHealthDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastDeviceStateDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="healthCheckInterval" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sensor" eSuperTypes="#//Device">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentRange" eType="#//SensorRange"
        defaultValueLiteral="NORMAL"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="affectedBy" upperBound="-1"
        eType="#//Actuator" eOpposite="#//Actuator/affects"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minReadable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxReadable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastMeasurement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowFatalThreshold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowCriticalThreshold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="highCriticalThreshold"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="highFatalThreshold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastMeasurementDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="readInterval" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actuator" eSuperTypes="#//Device">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="#//ActuatorState"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="performance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="affects" upperBound="-1"
        eType="#//Sensor" eOpposite="#//Sensor/affectedBy"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effect" eType="#//ActuatorEffect"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastActuatorStateDate"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ActuatorState">
    <eLiterals name="ON"/>
    <eLiterals name="OFF"/>
    <eLiterals name="UNKNOWN"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SensorRange">
    <eLiterals name="LOW_FATAL"/>
    <eLiterals name="LOW_CRITICAL"/>
    <eLiterals name="NORMAL"/>
    <eLiterals name="HIGH_CRITICAL"/>
    <eLiterals name="HIGH_FATAL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DeviceHealth">
    <eLiterals name="OK"/>
    <eLiterals name="DEGRADED"/>
    <eLiterals name="ERROR"/>
    <eLiterals name="UNKNOWN"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DeviceState">
    <eLiterals name="ACTIVE"/>
    <eLiterals name="INACTIVE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ActuatorEffect">
    <eLiterals name="POSITIVE"/>
    <eLiterals name="NEGATIVE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Time">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
</ecore:EPackage>
